# Prefer a pinned base (not develop). If you must use openg2p/openg2p-odoo-package, pin a fixed tag/digest.
FROM openg2p/openg2p-odoo-package:17.0-develop

# Copy addon repos into the image (frozen snapshot at build time)
COPY ./openg2p-program /opt/bitnami/odoo/extra-addons/openg2p-program
COPY ./openg2p-registry /opt/bitnami/odoo/extra-addons/openg2p-registry
COPY ./openg2p-addons /opt/bitnami/odoo/extra-addons/openg2p-addons
COPY ./odoo-openg2p-bot /opt/bitnami/odoo/extra-addons/odoo-openg2p-bot
COPY ./server-tools /opt/bitnami/odoo/extra-addons/server-tools
COPY ./connector /opt/bitnami/odoo/extra-addons/connector
COPY ./openg2p-g2p-bridge /opt/bitnami/odoo/extra-addons/openg2p-g2p-bridge
COPY ./openg2p-g2p-bridge-bank-connectors /opt/bitnami/odoo/extra-addons/openg2p-g2p-bridge-bank-connectors
COPY ./openg2p-g2p-bridge-celery-beat-producers /opt/bitnami/odoo/extra-addons/openg2p-g2p-bridge-celery-beat-producers
COPY ./openg2p-g2p-bridge-celery-workers /opt/bitnami/odoo/extra-addons/openg2p-g2p-bridge-celery-workers
COPY ./openg2p-g2p-bridge-example-bank /opt/bitnami/odoo/extra-addons/openg2p-g2p-bridge-example-bank



RUN /opt/bitnami/odoo/venv/bin/python -m pip install --no-cache-dir schwifty
