[options]
admin_passwd = ${ODOO_MASTER_PASSWORD}
db_host = postgresql
db_port = 5432
db_user = odoo
db_password = ${POSTGRES_PASSWORD}
db_name = openg2p

proxy_mode = False
list_db = False
dbfilter = ^openg2p$

addons_path = /opt/bitnami/odoo/addons,/opt/bitnami/odoo/extra-addons
without_demo = all

data_dir = /bitnami/odoo
log_level = info

http_port = 8069
longpolling_port = 8072